#!/run/current-system/sw/bin/python
from os import listdir, system
from os.path import isfile, join
import random

mypath = "connections/"

ovpnfiles = filter(lambda f: isfile(join(mypath, f)) and f.endswith(".ovpn"), listdir(mypath))

random_file = random.choice(list(ovpnfiles))

command = "openvpn --config '" +\
          join(mypath, random_file) +\
          "' --writepid /run/openvpn/home.pid"

print(" --- connecting to " + random_file + " ---")
system(command)
