#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    enable_ale = true
    enable_vimfiler_welcome = false
    windows_smartclose = ''
    escape_key_binding = ''
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    disabled_plugins = ["vim-surround"]
#colorscheme = "one"
#colorscheme_bg = "light"
    colorscheme = "gruvbox"
    #colorscheme_bg = "dark"

[[custom_plugins]]
    repo = "michelrandahl/simple-vim-surround"
    merged = false

[[custom_plugins]]
    repo = "mtikekar/nvim-send-to-term"
    merged = false

#[[custom_plugins]]
#    repo = "elmcast/elm-vim"
#    merged = false

[[custom_plugins]]
    repo = "autozimu/LanguageClient-neovim"
    merged = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#lua"

[[layers]]
name = "lang#elm"

[[layers]]
name = "lang#elixir"

[[layers]]
name = "lang#clojure"

[[layers]]
name = "lang#idris"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#haskell"

[[layers]]
name = "colorscheme"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#json"

[[layers]]
name = "fzf"

[[layers]]
name = "git"

#[[layers]]
#name = "lsp"
#filetypes = [ "python" ]

