[colors.bright]
black=   "#000000"
red=     "#de3d35"
green=   "#2e853a"
yellow = "#b58900"
blue=    "#2f5af3"
magenta= "#a00095"
cyan=    "#2e852a"
white=   "#ffffff"

[colors.normal]
black=   "#000000"
red=     "#de3d35"
green=   "#2e853a"
yellow = "#b58900"
blue=    "#2f5af3"
magenta= "#a00095"
cyan=    "#2e852a"
white=   "#bbbbbb"


[colors.primary]
background = "#f8f8f8"
foreground = "#2a2b33"

[font]
size = 10

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.normal]
family = "Source Code Pro"
style = "Regular"
